name: "🚀 Feature"
description: "새로운 기능 개발 및 개선 작업"
title: "[FEATURE] "
labels: [ "Feature" ]
body:
  - type: textarea
    attributes:
      label: 💡 기능 요구사항 및 구현 계획
      placeholder: 구현하려는 기능의 설명과 작업 계획을 적어주세요.
    validations:
      required: true
